### ISSUE TITLE
Add some sanity tests

### ISSUE THREAD

**Issue by hhorak** [sclorg/thermostat-container#6]
Testing thermostat is not easy, but we can have some general tests at least, so we know thermostat is installed properly and SCL is enabled. Checking usage output and binary availability may be start..

**Comment by pkubatrh** [comment]
Some basic tests for thermostat-16-storage are part of https://github.com/sclorg/thermostat-container/pull/14

Basic tests for thermostat-16-agent will be included in a different PR.

**Comment by pkubatrh** [comment]
thermostat-16-agent tests are available via #15

**Comment by omron93** [comment]
Both mentioned PRs are merged. So closing this issue.

Feel free to reopen.
